### ISSUE TITLE
Run Applications?

### ISSUE THREAD

**Issue by dancaer69** [adamnew123456/SmallWM#9]
Is possible to start applications except the shell command? I tried bind a key but it doesn't work. I tried for e.g to start smplayer using smplayer=p, but nothing happens when press "super+p" or "p" key. I also tried with exit-wm=p, to test the key but also doesn't work. 
So, how to start an application in smallwm?

**Comment by adamnew123456** [comment]
`exit-wm` not working is a documentation bug, the name used in the configuration is actually  `exit`. I just pushed an update for that in c2dc72a.

For launching applications it's best to use an external launcher like xchainkeys or xbindkeys. They're more flexible than the current SmallWM key binder since they support key chaining and more modifier keys. The keyboard config options are only there to customize the WM-specific actions that you can't invoke from outside.
